spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    h2-ds1:
      url: jdbc:h2:file:./data/demo1
      driverClassName: org.h2.Driver
      username: sa
      password: password

    h2-ds2:
      url: jdbc:h2:file:./data/demo2
      driverClassName: org.h2.Driver
      username: sa
      password: password

  jpa.database-platform: org.hibernate.dialect.H2Dialect